# Introduction for book {#intro}

The title of this book is numerically encoded.

Imagine you live in the old times where no computer or printing technology yet exist and books are written by hand. You are writing a very important book for the goodness of humanity on earth. Fans of evil also looks for ways to distort this good message as they are not fan of humanity. Over it is nineteen. You also want to make sure that your book remains intact and not even a single letter of it is changed by the publishers in the future copies of your book, even when you are no longer living. How can you you succeed that? Not to mention, at old times, communication is very limited and prone to distortions. 

By the way, have you already realized the encoding of the title and got its message by now? If not, I will explain it later or you can give it one more try! Let's get back to the subject for now with a more relevant technical example in the next section.

## A more technical example

This problem is similar to error control coding (ECC) in telecommunications of science. Basically, when signals are sent at the transmitter side via wires or air or in any other medium, they are distorted by noise from various sources. This causes the transmitted signal to be received as distorted at the receiver side. Consequently, a wrong message is received than original transmitted one. ECC is a telecommunications field that particularly aims to deal this specific problem. As an example, a very simple algorithm of an ECC is the parity-check codes, which is still in use in some communication protocols. As an example of its implementation, let's say we want to send two digit binary numbers 1 and 0 from the transmitter. So, the message to be sent is "10". This is not decimal ten but binary one and zero in two binary digits. If we send this message as is and if one of the binary digits (bits) are distorted and thus changes during the transmission then at the receiver side we might obtain an incorrect message such as "11" instead of the original message"10". Without asking if the message is correct or not to the receiver side, we have no way of knowing if the message is correctly received or not. Because we cannot ask to the transmitter for this as it would make meaningless communicating remotely. If we had the ability to ask the correct message directly, then why would one send the message from a distance at the first place. 
ECC science provides solutions for this problem. This time, Let's encode the exemplary message "10" with a simple *even* parity-check algorithm. Instead of sending the original two bits message "10", we encode it as "101" by **concatenating** one more redundant digit to the end of the message. This makes the sum of all the digits of the message as two which is an even number or, in other words, it is now divisible by 2. The last concatenated bit (binary digit) is the parity bit for detecting the error if occurs. So at the receiver side, if we already know the coding system such that the original message was always encoded by even-parity check algorithm, then at the receiver side, we have the ability to understand if the message is distorted or not at some level. Lets say the message was again distorted by one bit and we received it as "111" instead of the original transmitted and encoded message "101". The receiver checks the sum of the digits, because there is a ECC system in the communication now. The sum is 3 and this is not an even message as it must have always been so. Therefore, based on the system of the encoded communication, the receiver understands that the message contains error and do not trust this message and discards it in this simple case. ECC is a large field and there are much more complex algorithms that are also able to correct the errors in the message. 

It is also worth emphasizing that in the simple ECC example, we observed an algorithm that defines the set of rules and we also observed **concatenation** operation as part the algorithm. A communication with a such a design is generally referred as a communication **system**.  


Interesting enough, I have my PhD in ECC and developed and published my own ECC algorithms in the field. Therefore, when I realized about 19 based coding system in the text of Quran, my first impression was that, all-knowing God might have encoded the text of Quran similar to ECC to assure us that the message is always intact and not changed at all. This is particularly important in our current time in which materialism and advance science are flourished and people of knowledge always wants to see evidences to convince on any topic. If there is a coding system in the text of Quran that can be practically tested, then this would be important evidence of the message of God for minds of this time who got used to approve only testable and reproducible facts.

## Decoding the encoding

After the above long technical example of coding, it is time to explain the coding in the title of this book for the readers who could not find out it yet. The number of letters of the title "Reproducible Miracle" is 19. I had given a hint on this by writing the number 19 in a short sentence above as "Over it is nineteen" out of context. The number of letters in any title would normally be a random number. However, I also mentioned the key number for my encoding in the text in a unique and bizarre way. If the number of letters in the title is equal to the number stated in the book then this is very unlikely to occur by chance but most likely to be designed that way by the author. As the author of this book, I can assure you that I designed it deliberately! If there are many other similar encodings in the book. then you can easily come to the conclusion that, these are designed patterns and not random coincidences.


In fact, if you are careful enough, you might have realized the second coding in the title of this sub-section! Since you learned the approach from the coding in the main title, I will leave the second one to you and will not explain it here again!

One thing to note from these two encodings by 19 in this small text portion of the book should tell you that these two events can almost only be done by design but not with a mere coincidence. As the author of this book, I tell you that both of the titles were different than the current forms. They were longer and more descriptive. However, I wanted to demonstrate codings in a text in real time while you are reading about it as examples. As a result, the titles ended up in different forms but with the identical meanings to their longer basic versions.

Also, I want to share my personal feelings about the main title of this book. It was about two times more of the current title. Then, I wanted to match it exactly to 19 by adjusting the number of letters in it and tried a very short one. At my first attempt, I tried the current title "Reproducible Miracle" and it just matched to 19. I was quite surprised and again **personally** thought that this particular title is also not a mere coincidence and it was meant to be so. My own impression led me to the conclusion that the title should be as is and it was beyond my personal preference. God knows best and this is just my gut feeling on it. I will talk about the importance of its meaning later in more detail while discussing about the meaning of a miracle.

## Related verses of unchanged Quran and motivation

There is this unique verse that refers to number 19 with no **explicit** meaning.

> "Over it is Nineteen", Quran, 74:30. 

There is no other verse like this special one out of all the other 6348 verses. This states directly a number and focuses our attention to it without any other information in this independent verse. Scholars look at the other neighboring verses and **interpret** from the context that this number might be referring the number of guardian angels. It may well be correct but it may also be correct that this number is the key number *over it is (19)* a protective coding system was designed to present evidence that the text of Quran has been protected as promised by the Author of Quran. There are verses in Quran from which we understand that Quran is intact and will be unchanged and protected. 

> "We, indeed We, it is We who have sent down the Reminder, and indeed it is We who will preserve it.", Quran, 15:9

> "This is the book in which there is no doubt, a guide for the conscientious.", Quran, 2:2

Also, here are some of the verses that mentions that the book is collected and arranged as in its form:

> "It is for Us to collect it and relate it.", Quran, 75:16

> "Those who rejected said, "If only the Quran was sent down to him in one go!" It was done as such so We could strengthen your heart with it, and We arranged it accordingly.", Quran, 25:32

These are some of the verses I came across and I consider them as supporting statements for the hypothesis of this book, which is to test whether the text of Quran was designed by a protective coding system and also unchanged since 632 for the last 1387 years.

The important point is that no matter you already believe that Quran is the book sent by God or not, we have scientifically proven very old book dated back to around 7th century and we read those verses that suggest that there might be a design  in the text of it. We also observer that the design of the text of this old book is also unique and there is no such book exist regarding the design of its text and organization. Then it is certainly worth testing to see if there is indeed any 19 based coding system in this old text. This is what exactly I attempted to do and witnessed that indeed there is a 19 based coding system in the text. I probably could not decode all the codings but I certainly have observed sufficient evidences to rationally come to this conclusion. 

## Summary 

In this book, I will provide reproducible examples of some of the important 19 based codings in the text of Quran. I provided all the programming scripts along with each evidence in order to make them testable to eradicate doubts on the historical and universal truths. For this, I will use R programming language (www.r-project.org) to provide reproducible tests. I had started this study with the intention to test some of the existing claims about the 19 based codings on the text of Quran around last Ramadan month of Muslims (around May 2019). Then, I also tried some of my own hypothesis, of which some of them have been validated. Then, I hypothesized more and validated more and ended up with this book. Since the tests I perform in this book based on open source software rather than a user interface based application or manually counting the numbers, anyone with a tiny level of programming experience can analyse my R codes and run them by simply copy paste operations in their computers and reproduce and witness the results that I will present in this book. Anyone who analyses the codes I will share in this book and run and test the results will attain to the level of knowledge, which is knowing the truth by heart. Otherwise, even if the existing acclaimed cases on 19 based codings within Quran are correct, minds and hearts are always in doubt as they are not easily testable by readers as it is almost not practical for most. For the ones with negative prejudices, this situation causes ignoring and not witnessing to the truth. It also lefts the Muslims who wants to test before believing it with a burden of testing the claims manually, which is almost impractical for 99% of them. End result of this situation is a big barrier between a universal truth and humanity. I mainly aim to demonstrate reproducible tests on the 19 based codings of the text of Quran and provide the software material so that the ones who wish to try themselves can easily perform and witness the tests and attain to the knowledge of the truth by heart without any doubt. I also calculate the probability of observing the evidences by chance alone to make sure we have a rational conclusion over the observations in the end.



## Can we believe Quran without a 19 based system?

Of course, yes. I will talk about this later in detail during the discussions chapters in the end  of this book. Because, it is a long discussion and not the main point of this book and I do not want readers to be distracted by this argument Having said that, most of the Muslims took a position against 19 system on Quran and have negative impression on this topic as the authors of the first 19 system claim had manipulated Quran to make it match to their wrong 19 system. I wanted to clarify this point to clear the potential negative prejudices of most Muslims in the content of this book. This book is not about the wrong 19 system but a new one that is based on the whole text of the Arabic Quran that Muslims around the world keeps reading it for centuries and is still available as is on the bookstores that all the Muslims can buy online. I, myself, discovered all the evidences except a few. I mentioned those few already known evidences where I present in the book.


Muslims have the belief that Quran is intact and unchanged as it was revealed and completed 1387 years ago in 632. They have already acceptable reasons to believe it. First of all, almost all 1.5 billion Muslims have the same Arabic Quran and they claim that they follow it! I will come to that later as it is another important subject to talk about but not the place to elaborate in this section. The point is if you ask any Muslim haw many Arabic text of Quran exist, you will always get answer as **one**. While I was writing about this book, as an ordinary Muslim I wanted to make sure about it and searched internet and saw some claims that there are some exceptions. I am not able to investigate on that topic currently but it does not change the reality that almost all Muslims have the same exact Arabic text of Quran in the world and as an ordinary Muslim I was not even aware of such claims until I performed an intentional search on the topic. 


Second reason to believe that Quran is intact and managed to arrive to our time as unchanged is the system of *Hafiz* tradition. If you go any Muslim country, you will see that there are thousands of people called *Hafiz*. Hafiz is given as the title to the people who memorizes the whole Quran in Arabic by heart. Even if they are not Arabic speakers, they are able to memorize the whole Quran and precisely recite it. Considering all the Muslim countries, there may be tens of thousands of Hafiz people exist even at our current time of technology. Historical sources mentions that this is a tradition dates back to the time of Prophet Muhammad. There have been thousands of religions on earth from old times until now but there is only one book that has been fully and precisely memorized by tens of thousands of people on earth in the current time and before. I consider this fact as the second evidence that supports the belief of Muslims that the text of Quran is intact and unchanged.

There are also some very old Quran manuscripts that are dated back to the end of seventh century and even some parchment papers of Quran radiocarbon dated back to the time of the Prophet Muhammad by the carbon (The Birmingham Quran manuscript). One can search internet and get more information on them. I will not go into much detail on this as it requires another long and expert level scientific discussion.

The fourth evidence to believe that Quran is unchanged is its content. If you read the interpretation of Quran, one can judge herself but in my personal judgement, I have to state that the content is the best proof that it is the book from God. My heart calms down as I find answers for the meaning of my life and everything around me. Once you are convinced that these meanings are the word of God then there are verses, where God promises that Quran will be protected and there is no doubt in it.

Then why a 19 based coding would be important? Well, all the above points are mostly for ordinary Muslims who were raised as Muslims already. It is easier for them to accept all the above points but it might not be seen sufficient for non-Muslim readers of Quran. Such a 19 based coding system of the text of Quran, which could not be able to design by the people of that time, that proves that the text of Quran is intact and unchanged since the completion of revelation in 632 can help convince people who have doubts about it.
